package main

import "fmt"

func main() {
	booll()
	fmt.Println(CamelToSnakeCase("HelloWorld"))
	fmt.Println(CamelToSnakeCase("helloWorld"))
	fmt.Println(CamelToSnakeCase("camelCase"))
	fmt.Println(CamelToSnakeCase("CAMELtoSnackCASE"))
	fmt.Println(CamelToSnakeCase("camelToSnakeCase"))
	fmt.Println(CamelToSnakeCase("hey2"))
	fmt.Println(CheckNumber("Hello"))
	fmt.Println(CheckNumber("Hello1"))
	fmt.Println(CountAlpha("Hello world"))
	fmt.Println(CountAlpha("H e l l o"))
	fmt.Println(CountAlpha("H1e2l3l4o"))
	fmt.Println(rev("Hello World"))
	fmt.Println(FixSingleQuotes("                 hello '     there          '   how    ' have '    you been   "))
	fmt.Println(FixSingleQuotes("                 And there you have it, he said '     hello      there          '   how    ' have '    you been   "))
	fmt.Println(JoinModifiers([]string{"(cap,", "3)", "(low,", "5)", "(up,", "9)"}))
	fmt.Println(ProcessCase([]string{"wise", "(cap)", "lent", "(low)", "james", "(up)"}))
	fmt.Println(ProcessCase([]string{"BOY'S", "NAME", "IS", "PETER", "PAN", "(low,", "5)"}))
	fmt.Println(ProcessCase([]string{"cAP", "uP", "jAMES", "iS", "nOW", "(cap,", "5)"}))
	fmt.Println(ProcessBase([]string{"1e", "(hex)", "1E", "(hex)"}))
	fmt.Println(ProcessBase([]string{"10", "(bin)"}))
	chem()
	fmt.Println(Reverse("golang"))
	fmt.Println(CountVowels("education"))
	fmt.Println(UnderscoreSpaces(("go is fun")))
	fmt.Println(CapitalizeWords("go is awesome"))
	fmt.Println(CountLetter("banana", 'a'))
	fmt.Println(RemoveDigits("a1b2c3d4"))
	fmt.Println(RemoveDigits("a1b2c3d4 i5s6 s7i8m9p0l1e2"))
	fmt.Println(LastWord("go is super fun   "))
	fmt.Println(ToggleCase("GoLanG"))
	fmt.Println(UniqueChars("banana"))
	fmt.Println(ExpandChars("go", 3))
	fmt.Println(ReverseVowels("education"))
	fmt.Println(NormalizeSpaces("go   is   fun   "))
	fmt.Println(CleanPalindrome("nurses run"))
	fmt.Println(MostFrequentChar("mississippi"))
	fmt.Println(MergeString("abc", "12345"))
	fmt.Println(ReverseUnicode("he😊llo"))
	fmt.Println(Anagram("Listen", "Silent"))
	Capit()
	off()
	fmt.Println(hexToDec("I have 1E (hex) files hidden at home."))
	fmt.Println(power(5, 2))
	prob()
	fmt.Println(punct(" , Hello ,world"))
	fmt.Println(punct("Hello ,world . . . ..."))
	fmt.Println(quote(`    i am a 'boy ' and i love 'food ' so ' much' `))
	fmt.Println(rmDuplicate("boys and girls can be boys friends and altogether"))
	fmt.Println(MergeStrings("abc", "12345"))
	fmt.Println(UpperCaseLastN([]string{"This", "is", "so", "exciting"}, 3))
	testcount(1)
	hello()
	fmt.Println(Transform("F3*av*our:is, coming?today"))
	fmt.Println(singleQ(`   go " ' lang burst out ' "    here    her p    `))
	fmt.Println(Punc(singleQ(`   go ., "   '  n  ,, lang burst out : '  "  ,here    her p . . .   `)))
	fmt.Println(Tokenize("1E(hex) files added"))
	fmt.Println(Tokenize("hello ,world"))
	tutorial()
	fmt.Println(do(9))
}
